version: "3"
services:
  jenkins:
    image: 'bitnami/jenkins:latest'
    restart: unless-stopped
    networks:
      - mybridge
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/bitnami'

networks:
  mybridge:

volumes:
  jenkins_data:
  shoeb
